### PR TITLE
feat!: Bump Terraform and AWS provider MSV to `1.3` and `5.0` respectively, add latest releases and set `3.103.0` as the default version

### PR DESCRIPTION
**Pull request by mikecook**
## Description
- Bump Terraform and AWS provider MSV to `1.3` and `5.0` respectively
- Add latest releases and set 3.103.0 as the default version

## Motivation and Context
Resolves several CVEs mentioned in datadog-serverless-functions repo

## Breaking Changes
Known issue https://github.com/DataDog/datadog-serverless-functions/issues/684

### CODE REVIEW

**Comment by mikecook** [comment]
Might want to bump `runtime` default too. I'm not sure if 3.8 is supported for the latest function version.

**Review by bryantbiggs — APPROVED** [review]
thank you!

**Comment by antonbabenko** [comment]
This PR is included in version 6.0.0 :tada:

**Comment by gpdenny** [comment]
@mikecook were you able to get this running with the default runtime of python3.8? 
I think the default runtime might need to be bumped to python3.11. Ran into https://github.com/urllib3/urllib3/issues/2168 related errors unless I increased to python3.11.

**Comment by gpdenny** [comment]
Raised #37 as I think this is the case.

**Pull request merged**
